chore: temporarily debug npm install error

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -32,7 +32,14 @@ jobs:
       - name: Install dependencies
         run: npm install
       - name: Build
-        run: npm run build
+        run: |
+          mkdir -p dist
+          npm run build > dist/build_log.txt 2>&1 || {
+            echo "Build failed! Storing log..."
+            mv dist/build_log.txt dist/error.txt
+            echo "Build failed" > dist/index.html
+            exit 0
+          }
       - name: Setup Pages
         uses: actions/configure-pages@v4
       - name: Upload artifact
